os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - redis-server
osx_image: xcode8.3
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update && brew install redis; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi
before_script:
  - redis-server --port 6379 > /dev/null &
script:
  - mv .Package.test.swift Package.swift
  - swift --version
  - swift build
  - swift build -c release
  - swift test
after_success:
  - eval "$(curl -sL https://reswifq.github.io/scripts/codecov)"
notifications:
  email:
    on_success: never
    on_failure: change
