os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - redis-server
osx_image: xcode8.3
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew update && brew install redis; fi
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
before_script:
  - redis-server --port 6379 > /dev/null &
script:
  - mv .Package.test.swift Package.swift
  - swift build
  - swift test
after_success:
  - eval "$(curl -sL https://reswifq.github.io/scripts/codecov)"
notifications:
  email:
    on_success: never
    on_failure: change
